version: '2'
services:
  app:
    build: .
    command: foreman start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - redis
      - db
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: 'redis://redis:6379/12'
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
