version: '2'
services:
  haproxy:
    image: haproxy:latest
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./config/server.pem:/usr/local/etc/haproxy/server.pem
    links:
      - www1
      - www2
    ports:
      - "80:80"
      - "443:443"
  www1:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/public
      - ./config/server.crt:/etc/nginx/server.crt
      - ./config/server.key:/etc/nginx/server.key
    links:
      - web
  www2:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/public
      - ./config/server.crt:/etc/nginx/server.crt
      - ./config/server.key:/etc/nginx/server.key
    links:
      - web
  web:
    build: .
    command: bundle exec foreman start web
    volumes:
      - .:/app
    links:
      - redis
      - db
    depends_on:
      - redis
      - db
    environment:
      - REDIS_URL=redis://redis:6379/12
      - RAILS_LOG_TO_STDOUT=true
  worker:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    links:
      - redis
      - db
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: 'redis://redis:6379/12'
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
